### ISSUE TITLE
NoMethodError (undefined method unescape' for URI:Module)

### ISSUE THREAD

**Issue by Omen90** [xelkano/redmine_xapian#130]
### Issue
Searching in files / attachments ends with the error below:

[743dcc72-a2fd-472c-ae0d-5288be78bd43] NoMethodError (undefined method `unescape' for URI:Module):
[743dcc72-a2fd-472c-ae0d-5288be78bd43]   
[743dcc72-a2fd-472c-ae0d-5288be78bd43] plugins/redmine_xapian/lib/redmine_xapian/xapian_search.rb:106:in `block in xapian_search'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] plugins/redmine_xapian/lib/redmine_xapian/xapian_search.rb:92:in `each'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] plugins/redmine_xapian/lib/redmine_xapian/xapian_search.rb:92:in `xapian_search'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] plugins/redmine_xapian/lib/redmine_xapian/xapian_search_service.rb:32:in `search'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] plugins/redmine_xapian/lib/redmine_xapian/patches/attachment_patch.rb:74:in `search'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] plugins/redmine_xapian/lib/redmine_xapian/patches/attachment_patch.rb:59:in `search_result_ranks_and_ids'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/search.rb:119:in `block in load_result_ids'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/search.rb:117:in `each'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/search.rb:117:in `load_result_ids'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/search.rb:107:in `block in load_result_ids_from_cache'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/search.rb:106:in `load_result_ids_from_cache'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/search.rb:92:in `result_ids'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/search.rb:65:in `result_count'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] plugins/redmine_xapian/lib/redmine_xapian/patches/search_controller_patch.rb:137:in `index'
[743dcc72-a2fd-472c-ae0d-5288be78bd43] lib/redmine/sudo_mode.rb:61:in `sudo_mode

### Redmine info

Environment:
  Redmine version               5.0.3.stable
  Ruby version                     3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                      6.1.7
  Environment                     production
  Database adapter             Mysql2                    
Redmine plugins:
  additionals                         3.0.7
  redmine_agile                    1.6.4
  redmine_checklists             3.1.21
  redmine_theme_changer    0.6.0
  redmine_x_lightbox2          1.0.0
  redmine_xapian                  3.0.1

### My solution

Because of `URI.escape` and `URI.unescape` has been [deprecated](https://github.com/ruby/ruby/commit/238b979f1789f95262a267d8df6239806f2859cc) I used CGI::unescape instead of URI method. I don't know if it will be compatible with earlier Ruby versions. 

Thanks

**Comment by picman** [comment]
Thank you very much for pointing that out. I think, that `CGI::unescape` results differ from `URI.unescape`. `URI::Parser` should provide exactly the same output.

```ruby
p = URI::Parser.new
p.unescape(url)
```
