### ISSUE TITLE
Missing host to link to! Error

### ISSUE THREAD

**Issue by shawndibble** [xelkano/redmine_xapian#71]
So I run the following: 
ruby plugins/redmine_xapian/extra/xapian_indexer.rb

and it goes through and performs an index. I get a whole bunch of warnings like the following, but it still cycles through:
`svn: warning: W160013: URL 'https://svn.OMIT.local/svn/icw/branches/drop5/branches/drop5/2.%20System%20Design%20and%20Implementation/02.%20Documents/OMIT_Delivery' non-existent in revision 13713`

But then at some point, it just craps out and gives me a big error as follows and I don't know how to begin to fix this issue

```
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.4/lib/action_dispatch/http/url.rb:45:in `full_url_for': Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true (ActionView::Template::Error)
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.4/lib/action_dispatch/http/url.rb:35:in `url_for'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:356:in `block in <class:RouteSet>'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:815:in `call'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:815:in `url_for'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:282:in `call'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:347:in `block (2 levels) in define_url_helper'
```

Redmine setup
```
Environment:
  Redmine version                3.1.2.stable.14882
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.3
  easy_gantt                     1.3
  menu_link                      1.0.0
  msproject_import               0.4.0
  recurring_tasks                2.0.0-pre
  redmine_agile                  1.4.0
  redmine_checklists             3.1.3
  redmine_ckeditor               1.1.3
  redmine_default_assign         0.6
  redmine_email_fetcher          0.3.1
  redmine_importer               1.2.2
  redmine_issue_completion       0.0.2
  redmine_issue_evm              3.5.7
  redmine_issue_templates        0.1.1
  redmine_knowledgebase          3.1.0
  redmine_ldap_sync              2.0.8.devel.gc3a7f280ec
  redmine_monitoring_controlling 0.1.1
  redmine_my_page                0.1.9
  redmine_people                 1.2.0
  redmine_per_project_formatting 0.0.4
  redmine_pivot_table            0.0.4
  redmine_report_filters         1.2.4
  redmine_xapian                 1.6.5
  time_logger                    0.5.3
```

**Comment by picman** [comment]
Is it still relevant?
Please post a bigger chunk of the log. There is just one ocurence of calling *url_for* but *only_path* is set to *true* in the script.

**Comment by shawndibble** [comment]
nope, no longer getting this error.
